In [2]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
import numpy as np
import pandas as pd
from sklearn.model_selection import cross_val_score,GridSearchCV
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt
import warnings
from  pandas import DataFrame
from pandas import Series, ExcelWriter
import inspect
import os
warnings.filterwarnings("ignore")

In [13]:
cd "C:\Users\Administrator\Desktop"

C:\Users\Administrator\Desktop


In [14]:
data = pd.read_excel("child.xlsx","Sheet1")
data.shape

(53, 250)

In [15]:
X_open = data[data.columns[1:76]]
X_open_delta = data[data.columns[1:16]]
X_open_theta = data[data.columns[16:31]]
X_open_alpha = data[data.columns[31:46]]
X_open_beta = data[data.columns[46:61]]
X_open_gamma = data[data.columns[61:76]]
X_close = data[data.columns[76:151]]
X_close_delta = data[data.columns[76:91]]
X_close_theta = data[data.columns[91:106]]
X_close_alpha = data[data.columns[106:121]]
X_close_beta = data[data.columns[121:136]]
X_close_gamma = data[data.columns[136:151]]
X_rest = data[data.columns[1:151]]
X_MMN = data[data.columns[151:166]]
X_P3 = data[data.columns[166:181]]
X_task = data[data.columns[151:181]]
y = data["age_class"]

In [5]:
X_all = [X_open, X_close, X_rest, X_task]

In [6]:
X_freq = [X_open_delta, X_open_theta, X_open_alpha, X_open_beta, X_open_gamma,
          X_close_delta, X_close_theta, X_close_alpha, X_close_beta, X_close_gamma]

In [16]:
X_erp = [X_MMN, X_P3]

In [10]:
def retrieve_name(var):
    callers_local_vars = inspect.currentframe().f_back.f_locals.items()
    return [var_name for var_name, var_val in callers_local_vars if var_val is var]

In [17]:
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.svm import SVC
test_mean = []
for X in X_erp:
    skf = StratifiedShuffleSplit(n_splits=100, test_size=0.5)
    test = []
    for train_index, test_index in skf.split(X, y):  # 这里的Y一定要是分类变量，不能是连续的，这里只是抽样，后面可以用连续的y
        X_train, X_test = X.iloc[train_index], X.iloc[test_index]
        y_train, y_test = y.iloc[train_index], y.iloc[test_index]  # 这里用的是连续变量
        #X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2)
        param_grid = {"C": np.linspace(0.1, 10, 100)}
        gs = GridSearchCV(SVC(gamma='auto'), param_grid, cv=2)
        gs.fit(X_train, y_train)
        scores=cross_val_score(gs,X_train,y_train,scoring='accuracy',cv= 2)
        test_scores = gs.score(X_test, y_test)
        #print(scores)
        #print(test_scores)
        #print(gs.best_params_)
        test.append(test_scores)
    test_mean = np.mean(test)
    print(test_mean)
    a = retrieve_name(X)[0][2:]
    result = a + ".xlsx"
    results = DataFrame(test, columns = ["ACC"])
    results.to_excel(result)

0.5914814814814815
0.5755555555555556


In [57]:
print(test)

[1.0, 0.9393939393939394]


In [30]:
StratifiedShuffleSplit?

In [16]:
train_index

array([78, 65, 51, 35, 91, 12, 70, 43, 41,  7, 13, 30, 83, 69, 95,  8, 11,
       82,  6, 76, 54,  2, 32, 24, 89, 71,  4, 52, 87,  9, 26, 74, 75, 20,
       36, 55, 27, 56, 21, 16, 28, 88, 81, 31,  1, 39, 40, 84, 79, 59, 57,
       85, 22, 48, 60, 45, 10, 53,  0, 86, 33, 44, 61, 68, 37, 18, 29, 47,
       38, 14, 34, 17, 46, 90,  5, 92], dtype=int64)

In [10]:
from sklearn.svm import SVC
for X in X_freq:
    for i in range(10):
        X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2)
        param_grid = {"C": np.linspace(0.1, 10, 100)}
        gs = GridSearchCV(SVC(gamma='auto'), param_grid, cv=5)
        gs.fit(X_train, y_train)
        scores=cross_val_score(gs,X_train,y_train,scoring='accuracy',cv= 5)
        test_scores = gs.score(X_test, y_test)
        print(scores)
        print(test_scores)
        print(gs.best_params_)

[0.40909091 0.42857143 0.38095238]
0.4375
{'C': 6.2}
[0.40909091 0.38095238 0.38095238]
0.46875
{'C': 0.1}
[0.5        0.33333333 0.47619048]
0.375
{'C': 2.1}
[0.40909091 0.42857143 0.38095238]
0.34375
{'C': 1.2000000000000002}
[0.40909091 0.28571429 0.28571429]
0.46875
{'C': 0.1}
[0.40909091 0.33333333 0.33333333]
0.5
{'C': 5.2}
[0.40909091 0.52380952 0.52380952]
0.34375
{'C': 2.1}
[0.40909091 0.38095238 0.47619048]
0.5
{'C': 2.4000000000000004}
[0.45454545 0.38095238 0.42857143]
0.25
{'C': 1.7000000000000002}
[0.45454545 0.23809524 0.47619048]
0.46875
{'C': 1.8000000000000003}
[0.40909091 0.57142857 0.28571429]
0.40625
{'C': 5.6}
[0.36363636 0.38095238 0.42857143]
0.5
{'C': 0.1}
[0.36363636 0.33333333 0.38095238]
0.34375
{'C': 0.7000000000000001}
[0.45454545 0.47619048 0.47619048]
0.40625
{'C': 0.1}
[0.36363636 0.42857143 0.38095238]
0.46875
{'C': 0.1}
[0.40909091 0.38095238 0.47619048]
0.375
{'C': 3.3000000000000003}
[0.45454545 0.47619048 0.38095238]
0.34375
{'C': 3.1}
[0.5        

In [10]:
GridSearchCV?

In [8]:
for X in X_freq:
    from sklearn.svm import SVC
    from sklearn.model_selection import LeaveOneOut
    loo = LeaveOneOut()
    loo.get_n_splits(X)
    test = []
    pred = []
    for train_index, test_index in loo.split(X):
        #print("TRAIN:", train_index, "TEST:", test_index)
        X_train, X_test = X.iloc[train_index], X.iloc[test_index]
        y_train, y_test = y.iloc[train_index], y.iloc[test_index]
        param_grid = {"C": np.linspace(0.1, 10, 100)}
        gs = GridSearchCV(SVC(gamma='auto'),param_grid = param_grid)
        gs.fit(X_train, y_train)
        y_pred = gs.predict(X_test)
        pred.append(y_pred)
        test.append(y_test)
    name_excel = retrieve_name(X)[0][2:]
    result = name_excel+".xlsx"
    pred = DataFrame(pred)
    a = pd.concat([pred, y],axis=1)
    a.to_excel(result)

KeyboardInterrupt: 

In [19]:
a = retrieve_name(X)[0][2:]
a

''